#!/bin/bash 
#
# MakeNote makes a note in the right location in files with the correct name and filetypes
# as per my specifications
#
# MakeNote classID <enter>
# lectureID
# 
# classID       = CISC???, ????123
# lectureID     = "the theory of everything"


if [[ $# == 0 ]]
then
        echo "usage: mknote classID week_num <enter> num_LectureName"
        exit 0
elif [[ $# > 2 ]]
then
        echo "MakeNote: too many arguments" >&2
        exit 1
elif [[ $# < 2 && $# != 0 ]]
then
        echo "MakeNote: too few arguments" >&2
        exit -1
fi

cID="$1"
week="$2"
read name
lID="$(sed -E 's/ /_/' <<< $name)"

school_root="/Users/cain/.queens"
count=$(find $school_root/ | grep -E -c "$cID")
y=$(find $school_root/ | grep -E "$cID" | cut -d / -f 5)
year=${y:0:4}
echo $y

if [[ $count != 0 ]]
then
        path="$school_root/$year/$cID/Notes/$week/$lID"
        mkdir -p $path

        file="$path/$lID.tex"
        cp "$school_root/MISC/Scripts/MakeNote/stdnote.tex" $file 
        
        coursename=$(sed "1q;d" "$school_root/$year/$cID/$cID.mknote")
        echo $coursename
        sed -i "s/cID/$coursename/" $file 
        mkdir $path/figures
        echo $path
        exit 0 
else
        echo "MakeNote: $cID is not a course directory. 
        To add one, add it to its respective year directory in the school directory. ie. 'Queens/y2.2/$cID'">&2
        exit -2
fi


